; Script generated by Antigravity for ShanuFx Downloader
; See https://jrsoftware.org/isdl.php to download Inno Setup

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{B5A7E2C9-AF4D-4A4D-B682-A192E5ED02A1}
AppName=ShanuFx Downloader
AppVersion=1.0.0.0
AppPublisher=ShanuFx
AppCopyright=© 2026 ShanuFx. All rights reserved.
DefaultDirName={autopf}\ShanuFx Downloader
DisableProgramGroupPage=yes
LicenseFile=LICENSE
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=Output
OutputBaseFilename=ShanuFxDownloader_Setup
SetupIconFile=assets\icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist\ShanuFxDownloader.exe"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\ShanuFx Downloader"; Filename: "{app}\ShanuFxDownloader.exe"
Name: "{autodesktop}\ShanuFx Downloader"; Filename: "{app}\ShanuFxDownloader.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\ShanuFxDownloader.exe"; Description: "{cm:LaunchProgram,ShanuFx Downloader}"; Flags: nowait postinstall skipifsilent
